In [1]:
import numpy as np
import pandas as pd
import os

In [2]:
os.chdir("C:\\Users\\ACER\\Downloads\\Batch 75 Day14\\Batch 75 Day14\\")
df=pd.read_csv('Movie_regression.csv')
display(df)

,Marketing expense,Production expense,Multiplex coverage,Budget,Movie_length,Lead_ Actor_Rating,Lead_Actress_rating,Director_rating,Producer_rating,Critic_rating,Trailer_views,3D_available,Time_taken,Twitter_hastags,Genre,Avg_age_actors,Num_multiplex,Collection
0,20.1264,59.62,0.462,36524.125,138.7,7.825,8.095,7.910,7.995,7.94,527367,YES,109.60,223.840,Thriller,23,494,48000
1,20.5462,69.14,0.531,35668.655,152.4,7.505,7.650,7.440,7.470,7.44,494055,NO,146.64,243.456,Drama,42,462,43200
2,20.5458,69.14,0.531,39912.675,134.6,7.485,7.570,7.495,7.515,7.44,547051,NO,147.88,2022.400,Comedy,38,458,69400
3,20.6474,59.36,0.542,38873.890,119.3,6.895,7.035,6.920,7.020,8.26,516279,YES,185.36,225.344,Drama,45,472,66800
4,21.3810,59.36,0.542,39701.585,127.7,6.920,7.070,6.815,7.070,8.26,531448,NO,176.48,225.792,Drama,55,395,72400
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
501,21.2526,78.86,0.427,36624.115,142.6,8.680,8.775,8.620,8.970,6.80,492480,NO,186.96,243.584,Action,27,561,44800
502,20.9054,78.86,0.427,33996.600,150.2,8.780,8.945,8.770,8.930,7.80,482875,YES,132.24,263.296,Action,20,600,41200
503,21.2152,78.86,0.427,38751.680,164.5,8.830,8.970,8.855,9.010,7.80,532239,NO,109.56,243.824,Comedy,31,576,47800
504,22.1918,78.86,0.427,37740.670,162.8,8.730,8.845,8.800,8.845,6.80,496077,YES,158.80,303.520,Comedy,47,607,44000
505,20.9482,78.86,0.427,33496.650,154.3,8.640,8.880,8.680,8.790,6.80,518438,YES,205.60,203.040,Comedy,45,604,38000

In [3]:
display(df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 506 entries, 0 to 505
Data columns (total 18 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Marketing expense    506 non-null    float64
 1   Production expense   506 non-null    float64
 2   Multiplex coverage   506 non-null    float64
 3   Budget               506 non-null    float64
 4   Movie_length         506 non-null    float64
 5   Lead_ Actor_Rating   506 non-null    float64
 6   Lead_Actress_rating  506 non-null    float64
 7   Director_rating      506 non-null    float64
 8   Producer_rating      506 non-null    float64
 9   Critic_rating        506 non-null    float64
 10  Trailer_views        506 non-null    int64
 11  3D_available         506 non-null    object
 12  Time_taken           494 non-null    float64
 13  Twitter_hastags      506 non-null    float64
 14  Genre                506 non-null    object
 15  Avg_age_actors       506 non-null    int64
 16  Num_multiplex        506 non-null    int64
 17  Collection           506 non-null    int64
dtypes: float64(12), int64(4), object(2)
memory usage: 71.3+ KB

None

In [4]:
display(df.describe())

,Marketing expense,Production expense,Multiplex coverage,Budget,Movie_length,Lead_ Actor_Rating,Lead_Actress_rating,Director_rating,Producer_rating,Critic_rating,Trailer_views,Time_taken,Twitter_hastags,Avg_age_actors,Num_multiplex,Collection
count,506.000000,506.000000,506.000000,506.000000,506.000000,506.000000,506.000000,506.000000,506.000000,506.000000,506.000000,494.000000,506.000000,506.000000,506.000000,506.000000
mean,92.270471,77.273557,0.445305,34911.144022,142.074901,8.014002,8.185613,8.019664,8.190514,7.810870,449860.715415,157.391498,260.832095,39.181818,545.043478,45057.707510
std,172.030902,13.720706,0.115878,3903.038232,28.148861,1.054266,1.054290,1.059899,1.049601,0.659699,68917.763145,31.295161,104.779133,12.513697,106.332889,18364.351764
min,20.126400,55.920000,0.129000,19781.355000,76.400000,3.840000,4.035000,3.840000,4.030000,6.600000,212912.000000,0.000000,201.152000,3.000000,333.000000,10000.000000
25%,21.640900,65.380000,0.376000,32693.952500,118.525000,7.316250,7.503750,7.296250,7.507500,7.200000,409128.000000,132.300000,223.796000,28.000000,465.000000,34050.000000
50%,25.130200,74.380000,0.462000,34488.217500,151.000000,8.307500,8.495000,8.312500,8.465000,7.960000,462460.000000,160.000000,254.400000,39.000000,535.500000,42400.000000
75%,93.541650,91.200000,0.551000,36793.542500,167.575000,8.865000,9.030000,8.883750,9.030000,8.260000,500247.500000,181.890000,283.416000,50.000000,614.750000,50000.000000
max,1799.524000,110.480000,0.615000,48772.900000,173.500000,9.435000,9.540000,9.425000,9.635000,9.400000,567784.000000,217.520000,2022.400000,60.000000,868.000000,100000.000000

In [5]:
print(df.dtypes)

Marketing expense      float64
Production expense     float64
Multiplex coverage     float64
Budget                 float64
Movie_length           float64
Lead_ Actor_Rating     float64
Lead_Actress_rating    float64
Director_rating        float64
Producer_rating        float64
Critic_rating          float64
Trailer_views            int64
3D_available            object
Time_taken             float64
Twitter_hastags        float64
Genre                   object
Avg_age_actors           int64
Num_multiplex            int64
Collection               int64
dtype: object

In [6]:
print(df.isna().sum())

Marketing expense       0
Production expense      0
Multiplex coverage      0
Budget                  0
Movie_length            0
Lead_ Actor_Rating      0
Lead_Actress_rating     0
Director_rating         0
Producer_rating         0
Critic_rating           0
Trailer_views           0
3D_available            0
Time_taken             12
Twitter_hastags         0
Genre                   0
Avg_age_actors          0
Num_multiplex           0
Collection              0
dtype: int64

In [7]:
print(df['Time_taken'].mean())

157.39149797570855

In [8]:
df['Time_taken'].fillna(value=df['Time_taken'].mean(),inplace=True)
print(df.isna().sum())

Marketing expense      0
Production expense     0
Multiplex coverage     0
Budget                 0
Movie_length           0
Lead_ Actor_Rating     0
Lead_Actress_rating    0
Director_rating        0
Producer_rating        0
Critic_rating          0
Trailer_views          0
3D_available           0
Time_taken             0
Twitter_hastags        0
Genre                  0
Avg_age_actors         0
Num_multiplex          0
Collection             0
dtype: int64

In [9]:
print(df.head())

   Marketing expense  Production expense  Multiplex coverage     Budget  \
0            20.1264               59.62               0.462  36524.125
1            20.5462               69.14               0.531  35668.655
2            20.5458               69.14               0.531  39912.675
3            20.6474               59.36               0.542  38873.890
4            21.3810               59.36               0.542  39701.585

   Movie_length  Lead_ Actor_Rating  Lead_Actress_rating  Director_rating  \
0         138.7               7.825                8.095            7.910
1         152.4               7.505                7.650            7.440
2         134.6               7.485                7.570            7.495
3         119.3               6.895                7.035            6.920
4         127.7               6.920                7.070            6.815

   Producer_rating  Critic_rating  Trailer_views 3D_available  Time_taken  \
0            7.995           7.94         527367          YES      109.60
1            7.470           7.44         494055           NO      146.64
2            7.515           7.44         547051           NO      147.88
3            7.020           8.26         516279          YES      185.36
4            7.070           8.26         531448           NO      176.48

   Twitter_hastags     Genre  Avg_age_actors  Num_multiplex  Collection
0          223.840  Thriller              23            494       48000
1          243.456     Drama              42            462       43200
2         2022.400    Comedy              38            458       69400
3          225.344     Drama              45            472       66800
4          225.792     Drama              55            395       72400

In [10]:
print (df.shape)

(506, 18)

In [11]:
df=pd.get_dummies(df,columns=['3D_available','Genre'],drop_first=True)
display (df.head())

,Marketing expense,Production expense,Multiplex coverage,Budget,Movie_length,Lead_ Actor_Rating,Lead_Actress_rating,Director_rating,Producer_rating,Critic_rating,Trailer_views,Time_taken,Twitter_hastags,Avg_age_actors,Num_multiplex,Collection,3D_available_YES,Genre_Comedy,Genre_Drama,Genre_Thriller
0,20.1264,59.62,0.462,36524.125,138.7,7.825,8.095,7.910,7.995,7.94,527367,109.60,223.840,23,494,48000,1,0,0,1
1,20.5462,69.14,0.531,35668.655,152.4,7.505,7.650,7.440,7.470,7.44,494055,146.64,243.456,42,462,43200,0,0,1,0
2,20.5458,69.14,0.531,39912.675,134.6,7.485,7.570,7.495,7.515,7.44,547051,147.88,2022.400,38,458,69400,0,1,0,0
3,20.6474,59.36,0.542,38873.890,119.3,6.895,7.035,6.920,7.020,8.26,516279,185.36,225.344,45,472,66800,1,0,1,0
4,21.3810,59.36,0.542,39701.585,127.7,6.920,7.070,6.815,7.070,8.26,531448,176.48,225.792,55,395,72400,0,0,1,0

In [12]:
x=df.loc[:, df.columns!='Collection']
display(x)

,Marketing expense,Production expense,Multiplex coverage,Budget,Movie_length,Lead_ Actor_Rating,Lead_Actress_rating,Director_rating,Producer_rating,Critic_rating,Trailer_views,Time_taken,Twitter_hastags,Avg_age_actors,Num_multiplex,3D_available_YES,Genre_Comedy,Genre_Drama,Genre_Thriller
0,20.1264,59.62,0.462,36524.125,138.7,7.825,8.095,7.910,7.995,7.94,527367,109.60,223.840,23,494,1,0,0,1
1,20.5462,69.14,0.531,35668.655,152.4,7.505,7.650,7.440,7.470,7.44,494055,146.64,243.456,42,462,0,0,1,0
2,20.5458,69.14,0.531,39912.675,134.6,7.485,7.570,7.495,7.515,7.44,547051,147.88,2022.400,38,458,0,1,0,0
3,20.6474,59.36,0.542,38873.890,119.3,6.895,7.035,6.920,7.020,8.26,516279,185.36,225.344,45,472,1,0,1,0
4,21.3810,59.36,0.542,39701.585,127.7,6.920,7.070,6.815,7.070,8.26,531448,176.48,225.792,55,395,0,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
501,21.2526,78.86,0.427,36624.115,142.6,8.680,8.775,8.620,8.970,6.80,492480,186.96,243.584,27,561,0,0,0,0
502,20.9054,78.86,0.427,33996.600,150.2,8.780,8.945,8.770,8.930,7.80,482875,132.24,263.296,20,600,1,0,0,0
503,21.2152,78.86,0.427,38751.680,164.5,8.830,8.970,8.855,9.010,7.80,532239,109.56,243.824,31,576,0,1,0,0
504,22.1918,78.86,0.427,37740.670,162.8,8.730,8.845,8.800,8.845,6.80,496077,158.80,303.520,47,607,1,1,0,0
505,20.9482,78.86,0.427,33496.650,154.3,8.640,8.880,8.680,8.790,6.80,518438,205.60,203.040,45,604,1,1,0,0

In [13]:
y = df['Collection']
display(y)

0      48000
1      43200
2      69400
3      66800
4      72400
       ...
501    44800
502    41200
503    47800
504    44000
505    38000
Name: Collection, Length: 506, dtype: int64

In [14]:
from sklearn.preprocessing import StandardScaler
sc_x=StandardScaler()
sc_x.fit_transform(x)

array([[-0.41978194, -1.2879095 ,  0.14421743, ..., -0.66452648,
        -0.48699468,  1.32854331],
       [-0.41733926, -0.59338101,  0.74026221, ..., -0.66452648,
         2.05341054, -0.7527041 ],
       [-0.41734159, -0.59338101,  0.74026221, ...,  1.50483093,
        -0.48699468, -0.7527041 ],
       ...,
       [-0.41344658,  0.11573841, -0.15812412, ...,  1.50483093,
        -0.48699468, -0.7527041 ],
       [-0.40776407,  0.11573841, -0.15812412, ...,  1.50483093,
        -0.48699468, -0.7527041 ],
       [-0.41500016,  0.11573841, -0.15812412, ...,  1.50483093,
        -0.48699468, -0.7527041 ]])

In [15]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.3,random_state=0)
print(x_train.shape)
print(y_train.shape)
print(x.shape)
print(y.shape)

(354, 19)
(354,)
(506, 19)
(506,)

In [16]:
from sklearn.svm import SVR
svr_poly = SVR(kernel ='poly', C= 1000)
svr_poly .fit (x_train,y_train)
print (svr_poly)

SVR(C=1000, kernel='poly')

In [17]:
print (y_test )

329     45200
371    100000
219     46000
403     16600
78      42400
        ...
4       72400
428     22000
385     14400
308     45600
5       57400
Name: Collection, Length: 152, dtype: int64

In [19]:
svr_poly_pred=svr_poly.predict(x_train)
print(svr_poly_pred)

[19608.24245477 49904.76989899 34743.63915774 52916.64562874
 31812.51030211 31732.759653   42250.18338784 29818.0636967
 25131.85668228 48455.93975485 59588.36978235 58238.31503479
 45180.82696608 40225.54692106 47709.20218941 51541.52442402
 46894.55337332 35926.11018508 54641.03316884 26717.17346113
 35477.87581005 57958.35515112 38550.47932398 28040.56295357
 35194.10394033 30822.43550772 43809.75440627 49856.04681626
 36674.10286124 38810.57104372 46264.06829166 43396.9084452
 33893.64951914 56539.40905653 43766.53987352 51025.11829053
 51995.50699068 35722.44115272 26995.82400911 40557.58166804
 52621.48985083 45970.80722376 62544.73159032 51015.43074828
 41619.09705032 37534.12446048 49625.58885984 54667.86743038
 47442.02206354 40111.19568063 55059.41561565 53601.33392416
 23874.98105234 46189.19834176 37215.04276668 54130.76336904
 43027.98377172 43548.01419425 48541.80309019 49856.85698894
 33936.31589968 42997.78304343 44687.39250015 28169.61317549
 28168.68411834 47792.27231168 38501.31890669 59719.44748392
 30282.50074495 29729.62368632 37539.77040145 33146.49794991
 42055.92153303 43090.61298204 27663.16613555 39823.03407715
 54375.53009145 39374.36750633 29685.59144436 44642.41991293
 47793.40181422 56691.77522467 37772.73007909 44514.4189042
 30117.81299126 41365.91686752 50171.8924089  32546.07146371
 48308.46338751 46632.26291218 44613.04890355 32552.51772609
 51937.5417681  55365.14950635 42397.06724033 23716.80121581
 47393.54307985 30516.95481498 19625.68193401 27648.28318422
 33019.75614007 59559.21556691 36810.9894434  32610.22311522
 52981.4205135  44130.41587112 37383.8858429  57251.02495985
 55056.99764214 41962.89435519 34811.21004492 48049.40521048
 44831.01054596 27347.03545521 43297.80242284 54879.57791003
 48271.35092653 33546.7278631  42413.60305164 34151.9102384
 28109.46628834 56761.75913586 36729.4545296  41619.46158288
 28911.6050463  30881.22142293 35197.5403908  37680.81976283
 46442.29519887 55858.25545055 49983.53200973 41575.99671832
 26211.07913425 53770.62309681 23358.58017739 53164.08856799
 52456.18504074 46339.6724774  48095.50719075 35115.49702784
 37206.71065844 47460.55388427 34098.04367988 48571.67612197
 53260.27725747 41230.71252081 21541.78099704 64795.97621564
 51510.35462667 41478.4970653  43361.95620102 31756.53734745
 45300.74584572 44212.10289994 52324.4768896  18794.30117151
 39311.27571211 59867.81272463 58039.0731966  46641.88213384
 56276.70740874 41626.99598225 36473.73026819 27367.5414109
 41180.76524818 56166.65469124 45670.30328208 38515.01844714
 27828.12606325 34752.35246435 56526.1674523  46254.65101795
 40448.57254039 33468.13178799 47963.07853408 26948.2301592
 50218.33038643 45695.08052796 35374.87220204 42603.44581012
 46127.49316367 45594.82708625 39289.54115532 63205.40648665
 35984.58364688 52805.20909389 50008.07055917 39441.29345299
 57831.5225473  40289.25930541 47448.43435286 38945.70043118
 35668.28729648 45882.56778954 56283.79260838 45797.87572446
 32450.56839979 60241.15511372 34278.87951782 49443.43276748
 47679.69900646 45201.68537804 40694.31120571 39122.49679721
 38366.88217079 39042.18652052 44545.97110111 38250.92598175
 45592.04819816 51984.86746713 40194.27704715 39199.72477347
 29441.49016014 28595.10471388 30290.82173327 38099.53837804
 26209.49445479 44007.64783378 54652.59869727 31212.36986409
 43267.42836552 45788.88944386 29204.63867229 44354.14384369
 32902.2283594  55144.43822574 49756.18599816 60026.08991696
 41920.73457571 59305.72554314 48592.17209263 54908.85549436
 39074.1409326  52182.47474385 52165.55117408 54592.84008846
 43552.07357632 41421.8807966  47344.37213615 31274.87004712
 40425.37785202 49283.18154191 42545.72363187 21151.53396884
 52969.32532809 19801.88700732 31374.32709803 30715.14369412
 50344.60648849 50802.49989689 24112.41642814 24082.31245928
 50412.7631527  52684.26693059 33169.7595819  38591.96492816
 33691.71021562 48680.99321823 51895.66425563 55460.04194004
 59784.84189003 41156.56537951 41174.46800272 34691.1723719
 28679.29547221 31914.54304694 33470.25502197 21439.48906259
 48661.11730572 47949.81232961 48719.15053338 42551.38096118
 44349.72105092 58724.12972183 51914.77654165 27598.5504853
 46420.9895063  56146.45811379 28951.94032261 34802.16629855
 54977.8016552  37468.26292183 21976.40402929 33183.90207131
 54218.88247191 33508.27442548 48976.50940036 29672.11176448
 48750.06824626 37581.01054208 31772.02098364 39657.08870178
 64482.61569732 41363.62436561 48155.77876762 54418.23859174
 63307.91439577 43146.86074352 41814.0886383  61623.39852944
 38304.21289991 23422.76921293 32147.87470572 42695.00787808
 30152.37897931 33299.83995366 49150.88725318 26789.00965354
 22813.2293614  41297.45167056 22472.92951367 51771.78927653
 22470.15630603 46920.94630561 46561.57783127 43142.35330177
 35455.02243346 31938.97752511 45148.77487428 51825.73341896
 57336.11116129 41579.3113702  35294.90477698 24331.0268067
 41840.16181409 49428.41833521 57222.07062844 36231.08438559
 44067.6890552  40890.31680274 27756.10188928 45629.98567795
 38074.09228401 61081.01474339 50243.96580526 46184.68775677
 32056.85753963 51364.08451649 36178.34079205 49638.53787079
 47355.88295517 55622.05680356 45467.49816399 52918.41788714
 27386.67554542 34832.96904135 38555.80443841 59684.67560979
 60051.87903904 39884.14586195 52598.84822751 41201.08675724
 30260.1008361  35284.86970746]

In [21]:
from sklearn.metrics import r2_score
from sklearn.metrics import mean_squared_error
accuracy=r2_score(svr_poly_pred,y_train)
rms=mean_squared_error(svr_poly_pred,y_train)
print(accuracy)
print(rms)

-0.571372531445657
163125746.563225

In [22]:
from sklearn.svm import SVR
svr_sigm = SVR(kernel ='sigmoid', C= 1000)
svr_sigm .fit (x_train,y_train)
print (svr_sigm)

SVR(C=1000, kernel='sigmoid')

In [23]:
svr_sigm_pred=svr_sigm.predict(x_train)
print(svr_sigm_pred)

[41910.3983586  41658.3012864  43273.88135123 41329.65873782
 43509.72967464 43513.59350433 42510.88145294 43625.74527819
 43589.20911935 41820.26765787 40622.39421847 40760.54074495
 42179.39126381 42727.92058662 41903.36785553 41478.3245087
 41992.26431021 43167.8865955  41142.88339627 43674.60103278
 43206.66808893 40793.30107087 42905.97755482 43670.43218206
 43238.57599355 43576.47047103 42331.84890838 41665.38841891
 43092.85255651 42876.83308881 42064.80867447 42383.19092976
 43351.40283136 40941.61278767 42337.74838683 41534.78211937
 41424.18409992 43183.3814766  43667.25646514 42685.17893064
 41358.95864766 42098.18946712 40321.50377822 41537.49939447
 42574.5055924  43010.79610642 41690.77563248 41136.39567836
 41931.2682833  42743.78522649 41094.99290557 41252.25217223
 43452.69853369 42072.21685217 43040.49126334 41198.05619097
 42421.56265308 42366.38113173 41808.48939336 41663.19939251
 43343.07772819 42427.62232127 42239.37170369 43667.21549212
 43669.2859051  41890.91577144 42909.07461286 40608.26617668
 43607.54879554 43624.12824492 43008.75826902 43414.10421236
 42530.67035158 42414.20577698 43678.40733886 42769.88727782
 41171.77729533 42818.12225006 43627.67230309 42243.17672006
 41894.10414374 40923.83867228 42983.97338269 42257.10643212
 43604.47611952 42605.99270736 41626.17997568 43458.00387706
 41825.08359197 42020.91333949 42245.20067766 43457.28766643
 41433.83288463 41065.63930722 42491.83045808 43435.90307358
 41933.80129737 43587.16559591 41930.1021235  43667.45585743
 43424.5766758  40621.30265674 43082.5911297  43454.90062152
 41319.98856773 42300.94880496 43024.6303638  40864.9978262
 41099.65552836 42537.13699061 43270.62457258 41864.72465293
 42223.86039237 43676.78355299 42389.95246711 41127.78294504
 41841.09382551 43379.4640728  42487.37981025 43327.84360243
 43671.78927939 40917.37093015 43094.25383701 42577.76415218
 43659.20609361 43569.0677692  43236.58760745 42993.36574591
 42045.9221723  41013.50893181 41652.06012104 42581.42177461
 43656.42175714 41234.32433919 43379.63025852 41296.68953669
 41378.2282972  42051.91322158 41861.19682734 43243.26832534
 43042.87202272 41928.43500784 43335.50076642 41804.81832601
 41286.67127211 42621.89754563 42908.18943183 40100.3572161
 41481.20288663 42591.62610968 42386.97367246 43513.89700601
 42169.51729651 42292.47511268 41394.48588917 41185.65528097
 42825.4378791  40591.59949512 40781.02297192 42021.42917748
 40967.56328355 42575.57433012 43113.1544168  43679.51494188
 42630.84282637 40982.64339077 42126.97235101 42907.45222563
 43693.32835279 43274.44088721 40939.970817   42059.68657648
 42708.08952009 43387.10439668 41872.77861379 43674.67141778
 41624.18913431 42127.34420108 43220.86806572 42471.35668629
 42080.01565258 42136.05488025 42828.36904134 40254.23395304
 43160.10919771 41339.330559   41646.1507891  42811.94640682
 40801.62322286 42720.26794712 41931.90129037 42866.41496444
 43184.64746047 42107.74552982 40967.23228855 42116.02694796
 43462.58156853 40554.99156911 43306.9219453  41708.41341544
 41903.10187459 42175.95599641 42677.95688178 42837.5146534
 42924.11231083 42847.76271514 42255.96986061 42935.43061987
 42138.27130852 41429.361075   42732.58431794 42837.58745191
 43643.21219408 43659.08166866 43596.5991933  42951.64704333
 43653.88748484 42310.49454014 41142.16353987 43543.49526444
 42394.39599259 42113.40057968 43647.38105328 42275.43772062
 43428.3369569  41089.17053549 41676.21648358 40583.33771797
 42542.47843865 40648.90516437 41801.61332597 41112.05183923
 42852.3087213  41407.49190594 41409.97961479 41145.09576612
 42364.05214362 42597.92993129 41941.30545089 43544.90034815
 42704.65379132 41729.5960924  42473.02597511 42766.49107704
 41320.65077281 42051.70395465 43540.172242   43579.12647464
 41608.77946596 41557.10826033 43496.71139265 43489.31770506
 41603.2863595  41349.60590179 43407.72162654 42898.87586797
 43361.51551288 41792.37647119 41432.88593499 41056.07738573
 40599.61744206 42625.86010456 42626.04520432 43284.9420096
 43662.71211429 43502.85336605 43379.88201417 42893.3399641
 41796.23937478 41875.52420592 41781.78687792 42477.06693428
 42276.30409365 40710.96942432 41436.83234312 43676.68074495
 42045.02702543 40975.61392146 43647.44345683 43268.9174831
 41108.35952782 43016.86785386 43064.02255755 43406.97191579
 41184.34398059 43376.4198164  41763.17366487 43633.58784662
 41788.11453357 43001.86597218 43508.10628334 42786.468169
 40131.42982087 42602.79227373 41851.55071259 41165.30459486
 40243.17630619 42413.12000607 42558.65622127 40413.51960028
 42930.21522562 43383.83347598 43488.6932142  42459.05929204
 43602.15659376 43395.78648914 41742.43978157 43667.52582898
 43271.50834607 42610.93850045 43199.24323713 41453.81991945
 43196.26869926 41989.72851102 42024.65064202 42410.26316699
 43210.11705893 43493.93887977 42188.053527   41445.43824476
 40857.92586478 42580.89270231 43226.77411919 43519.17686516
 42555.96650245 41712.8046468  40870.13277515 43140.66761178
 42307.72267585 42657.43331928 43681.00353996 42135.39007171
 42954.42204009 40471.1753298  41619.90454996 42070.40696375
 43489.28305322 41496.23074923 43140.0384567  41688.15349331
 41942.25884645 41038.12704557 42151.11254092 41327.69835378
 43681.60451136 43268.28681743 42903.92233495 40609.81752492
 40576.42918137 42766.5797306  41361.05264944 42623.05700358
 43600.94878735 43230.21168555]

In [24]:
from sklearn.metrics import r2_score
from sklearn.metrics import mean_squared_error
accuracy=r2_score(svr_sigm_pred,y_train)
rms=mean_squared_error(svr_sigm_pred,y_train)
print(accuracy)
print(rms)

-427.20467806433425
375102493.4191352

In [25]:
from sklearn.svm import SVR
svr_rbf = SVR(kernel ='rbf', C= 1000)
svr_rbf .fit (x_train,y_train)
print (svr_rbf)

SVR(C=1000)

In [26]:
svr_rbf_pred=svr_rbf.predict(x_train)
print(svr_rbf_pred)

[26805.1222741  46177.67586768 38267.94594922 47404.87269463
 36343.52518318 36285.41689447 42600.62560341 34950.33942648
 31369.89260314 45560.98615163 49772.54831899 49317.88662196
 44034.6536115  41509.61461291 45230.28574585 46853.56244762
 44853.63437685 39015.38365771 48057.09167549 32634.41039518
 38728.25743238 49242.49124195 40574.44222135 33630.32623636
 38567.59135567 35668.25042202 43366.05273891 46164.98457666
 39462.23070439 40716.15983311 44572.30971804 43182.06268593
 37732.89581061 48748.23981328 43349.00963496 46642.75938052
 47012.63354622 38878.68687134 32831.60790545 41665.33036346
 47275.79163973 44438.12707728 50686.68850938 46646.63044496
 42249.53239624 39985.9498131  46066.92789658 48047.79811045
 45102.15587023 41459.79356922 48195.11027583 47652.34156474
 30349.85919591 44533.47965994 39789.60290591 47867.99273072
 42985.9644182  43257.60724554 45588.45902795 46155.60633147
 37748.06371898 42981.27108973 43817.84204848 33724.69727661
 33727.34045309 45253.11145245 40539.53725968 49811.24479888
 35291.08251009 34875.65525597 39984.49650414 37247.75181249
 42493.68455672 43016.07797235 33353.69166994 41284.11066524
 47960.10802345 41036.29276319 34847.20675314 43791.0649091
 45268.41928687 48793.04745826 40117.46483344 43727.48143614
 35150.04443757 42130.05396815 46277.30084266 36841.86667665
 45441.07462654 44730.57773684 43771.71402252 36845.61721195
 47006.77653766 48324.30578807 42665.56146159 30225.81706075
 45067.36700119 35439.39402875 26821.68837115 33325.49878645
 37165.08184369 49738.29392969 39554.47632151 36889.14308401
 47416.96015974 43543.78518396 39892.99527831 48988.016427
 48217.1800129  42430.90714943 38318.52291173 45378.36736893
 43889.41041159 33110.44177718 43115.40954559 48189.49238394
 45481.16552404 37504.81285971 42663.92314051 37895.55301348
 33685.73795521 48822.43350294 39516.98622996 42262.14563092
 34290.59488173 35700.37907183 38564.82584015 40063.78896154
 44659.23238461 48504.45449914 46222.16716726 42235.11362615
 32233.95440349 47718.70620093 29932.36773227 47468.77855464
 47217.28461776 44588.26083481 45405.8427634  38510.94846102
 39789.53033627 45107.07200173 37869.16500161 45599.90015649
 47508.15015196 42062.53538992 28408.70719105 51346.68012034
 46838.34373556 42181.99137934 43164.07595261 36306.10781253
 44106.81286545 43586.48697507 47174.55686486 26165.65895677
 41003.14702563 49850.63487933 49249.08025885 44741.90071745
 48645.79767115 42261.06435663 39343.35854405 33130.43374295
 42048.91812134 48623.88020826 44276.61414287 40546.68605481
 33509.17114627 38277.16667805 48727.40856931 44541.25228018
 41646.46262382 37456.48829269 45333.13957744 32806.82518371
 46311.75327065 44301.62465868 38677.60978441 42780.57915416
 44508.50951497 44243.75582335 40993.14747644 50872.95711017
 39044.71124982 47349.39540706 46217.68500974 41076.92678589
 49172.31673093 41541.5297236  45110.9504737  40805.50389872
 38834.55180852 44395.48733069 48650.48778877 44350.7138683
 36771.64596207 49979.65969328 37951.23449103 45977.62860263
 45201.24444226 44039.91552893 41766.64763408 40870.37960702
 40465.93017925 40831.09423406 43752.51277511 40396.9176407
 44250.50009354 47029.13874484 41497.16038736 40941.71576245
 34682.12559048 34041.53376018 35274.48149578 40311.43860861
 32229.20820793 43466.5493887  48063.97701621 35918.74655835
 43104.44332822 44331.0366061  34500.61767389 43651.13781211
 37073.32430784 48243.60612461 46121.77096122 49941.25020464
 42411.66434047 49665.40405629 45604.4952348  48144.96982877
 40876.09812137 47106.27456699 47102.81044065 48023.55950777
 43252.13511441 42152.42850963 45054.34650412 35973.62608334
 41612.33698149 45924.75634432 42732.70519823 28084.140196
 47408.83479703 26963.56010519 36046.01450254 35585.13303508
 46357.42869663 46540.91535558 30556.57056493 30527.93550261
 46395.38769855 47287.01240232 37251.45289723 40588.81082683
 37584.03766036 45646.21712333 46960.77777183 48361.638005
 49820.80054974 42007.69670302 42025.17745085 38252.65423061
 34113.82739228 36413.44710614 37439.84090349 28337.54462842
 45645.11803572 45332.91134872 45632.04326871 42753.6919549
 43650.59201687 49485.32965336 47000.21845942 33301.48897536
 44635.43249116 48565.64321807 34301.08470242 38305.77981619
 48189.20476509 39945.22032526 28783.55749638 37261.70767158
 47878.81288682 37463.83404857 45790.80683225 34848.44457102
 45691.71854753 40000.07314882 36305.88818516 41188.25148303
 51260.59206939 42115.97494937 45419.43754181 47966.50398393
 50896.91072953 43064.70897355 42372.7652505  50404.84611431
 40428.58752296 29979.24464837 36577.3778227  42818.99729547
 35173.41236579 37333.28885174 45859.71817603 32677.17085276
 29478.28488373 42084.35970152 29200.10052234 46949.56102309
 29195.69945845 44867.40796698 44679.62701459 43049.23311915
 38717.87193044 36413.69442094 44040.77152401 46958.94109335
 49027.13726466 42236.28342276 38623.27795178 30730.31889121
 42387.11037059 45983.77546052 48988.90504006 39208.16852699
 43512.09230683 41874.89223639 33429.41418641 44274.13391363
 40297.17102037 50253.30152352 46315.53393905 44521.45322443
 36501.76294918 46774.20408876 39158.72174628 46066.93537238
 45069.41947149 48416.80366835 44186.98965528 47396.84366582
 33148.47237529 38331.21152344 40572.46767823 49787.94416379
 49930.409261   41329.27866581 47264.99960025 42039.0460261
 35258.308385   38624.37286583]

In [27]:
from sklearn.metrics import r2_score
from sklearn.metrics import mean_squared_error
accuracy=r2_score(svr_rbf_pred,y_train)
rms=mean_squared_error(svr_rbf_pred,y_train)
print(accuracy)
print(rms)

-6.492429563514898
230738573.38725612